################################
#       Language config        #
################################
language:
   Language: en
   Region: US

################################
#          Debug info          #
################################

debug: false