name: Quake
version: 0.1
main: fr.bretzel.quake.Quake
commands:
   quake:
      description: The main command of quake.
   lobby:
      description: Use this for return to lobby.
   sqlSet:
   sqlGet:
   test: